package artifact

import (
	"fmt"
	"sort"
	"strings"

	irv1 "github.com/libbusinessid/spec/gen/go/libbusinessid/ir/v1"
	"github.com/libbusinessid/spec/internal/features"
	"github.com/libbusinessid/spec/internal/limits"
)

// generatedBanner marks every document produced by `businessidc`.
const generatedBanner = "<!-- Generated by businessidc. Do not edit by hand: run `make generate`. -->"

// RenderIRDoc renders docs/ir.md, the exhaustive normative reference of the IR.
func RenderIRDoc() []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("%s", generatedBanner)
	w("")
	w("# LibBusinessID IR v1")
	w("")
	w("This document is normative. Together with `rules.proto`, `conformance.proto`,")
	w("`features.md`, the reference bundle and its conformance suite, it is sufficient")
	w("to implement an engine without reading the Go code of the compiler.")
	w("")
	w("Structural format version: **%d**.", SupportedFormatVersion)
	w("")

	w("## 1. Value types")
	w("")
	w("| Enum value | Meaning |")
	w("|---|---|")
	w("| `VALUE_TYPE_STRING` | A possibly absent sequence of Unicode code points. |")
	w("| `VALUE_TYPE_INTEGER` | A checked signed 64 bit integer that may be indeterminate. |")
	w("| `VALUE_TYPE_BOOLEAN` | A predicate result. |")
	w("| `VALUE_TYPE_CANONICALIZATION_STEP` | A transformation applied to the current value. |")
	w("| `VALUE_TYPE_ASSERTION` | An ordered format check. |")
	w("| `VALUE_TYPE_CHECKSUM_OUTCOME` | A tri-state checksum result. |")
	w("")
	w("`VALUE_TYPE_UNSPECIFIED` is refused at load time, like every other zero enum value.")
	w("")
	w("### 1.1 Absence")
	w("")
	w("A string view may be **absent**. Absence propagates: every string constructor")
	w("applied to an absent operand yields an absent result. Every predicate applied to")
	w("an absent operand yields `false`, except `IS_ABSENT`, which yields `true`.")
	w("Absence is never an error and never an exception.")
	w("")
	w("### 1.2 Indeterminate integers")
	w("")
	w("An integer expression is **indeterminate** when it cannot be evaluated: an absent")
	w("or empty operand, a code point outside the mapping domain anywhere in the view,")
	w("even at a position no weight pairs with, an index outside a")
	w("remainder table, or a complement operand outside `[0, modulus]`. An indeterminate")
	w("integer propagates through every integer operation and makes the enclosing")
	w("checksum node evaluate to `unsupported` with `unsupported_checksum`. It never")
	w("produces `invalid`: refusing a valid identifier is the most serious defect of the")
	w("project.")
	w("")

	w("## 2. Programs")
	w("")
	w("A `Program` is a typed acyclic graph serialized in topological order. Every")
	w("`Node.input_nodes` entry references a strictly lower index of the same program.")
	w("`root_node` designates the result of the program.")
	w("")
	w("| Program kind | Accepted root | Accepted operation categories |")
	w("|---|---|---|")
	w("| `PROGRAM_KIND_CANONICALIZATION` | `CANONICALIZATION_OP_KIND_SEQUENCE` | string (except `SUBJECT`), predicate, canonicalization |")
	w("| `PROGRAM_KIND_FORMAT` | `ASSERTION_OP_KIND_SEQUENCE` | string, predicate, assertion, `CALL_OP_KIND_FORMAT` |")
	w("| `PROGRAM_KIND_CHECKSUM` | any node producing a checksum outcome, never a `WHEN` branch | string, predicate, integer, checksum, `CALL_OP_KIND_CHECKSUM` |")
	w("")
	w("`Program.subject_node`, when present, produces `subject()` for a top level")
	w("invocation. A canonicalization program never declares a subject and never")
	w("declares a capture. `Program.captures` names nodes of a format program; a capture")
	w("reference is lowered to a direct node reference, so the list is metadata used for")
	w("diagnostics and for the per format capture limit.")
	w("")
	w("Nodes are re-evaluated at every reference: no memoization is observable. This")
	w("matters inside a canonicalization program, where `value()` designates the value")
	w("current at the moment the enclosing step runs. Each node evaluation, each")
	w("canonicalization step application and each program invocation consumes one unit")
	w("of the evaluation budget of %d steps. In addition, an operation that",
		limits.MaxStepsPerValidation)
	w("produces a string, and every canonicalization step, is billed one further")
	w("unit per started slice of %d produced code points. That charge is what",
		limits.CodePointsPerStep)
	w("bounds the memory a bundle can make an engine allocate: the total number")
	w("of code points materialized by one public operation can never exceed the")
	w("budget times %d. Exhausting the budget is an engine error.", limits.CodePointsPerStep)
	w("")
	w("The budget bounds an interpretation. An engine that compiles the rules into")
	w("native code ahead of time does not count steps: the graph is acyclic and the")
	w("call depth is bounded, so the emitted code terminates by construction, and the")
	w("bounds below are what its generator enforces instead. An engine that walks the")
	w("IR at validation time applies the budget as written. Section 2.4 of the")
	w("specification binds observable results, never the strategy that produces them.")
	w("")
	w("### 2.1 Calls")
	w("")
	w("`CALL_OP_KIND_FORMAT` runs a format program with the operand as its subject and")
	w("propagates the callee reason code and message key unchanged.")
	w("`CALL_OP_KIND_CHECKSUM` runs a checksum program with the operand as its subject")
	w("and propagates its outcome unchanged. In a called program, `value()` still")
	w("designates the canonical value of the identifier under validation.")
	w("")
	w("The call graph must be acyclic, must only connect programs of the same kind, and")
	w("its static depth must be at most %d.", limits.MaxCallDepth)
	w("")

	w("## 3. Operations")
	w("")
	for _, category := range features.Categories {
		ops := features.OpsByCategory(category)
		if len(ops) == 0 {
			continue
		}
		w("### 3.%d %s operations", categoryIndex(category)+1, titleASCII(string(category)))
		w("")
		for _, op := range ops {
			w("#### `%s`", op.Symbol)
			w("")
			if op.HCL != "" {
				w("Surface syntax: `%s`.", op.HCL)
				w("")
			}
			w("Output: `%s`.", valueTypeName(op.Output))
			w("")
			w("Operands: %s.", operandDescription(op))
			w("")
			w("Parameters: %s.", paramDescription(op))
			w("")
			w("Capabilities: %s.", capabilityList(op.Features))
			w("")
			w("%s", op.Doc)
			w("")
		}
	}

	w("## 4. Reason codes")
	w("")
	w("| Reason code | Status it may carry |")
	w("|---|---|")
	for _, name := range reasonCodeNames() {
		w("| `%s` | %s |", name, statusesFor(name))
	}
	w("")
	w("`REQUIRE` only accepts a reason code that proves an invalidity: `empty`,")
	w("`invalid_length`, `invalid_characters`, `invalid_format` and `country_mismatch`.")
	w("`CHECKSUM_OP_KIND_UNSUPPORTED` and `IdentifierDefinition.absent_checksum_reason`")
	w("only accept `unsupported_checksum` and `checksum_not_published`.")
	w("")

	w("## 5. Dispatch")
	w("")
	w("`trim ASCII` removes only `U+0009..U+000D` and `U+0020` at both ends. A kind")
	w("token matches `[a-z][a-z0-9_-]{0,63}` after trim and lower casing, a country")
	w("token matches `[A-Z]{2}` after trim and upper casing, and a declared prefix is 1")
	w("to %d ASCII alphanumeric characters compared case sensitively.", limits.MaxPrefixLength)
	w("")
	w("1. Normalize the kind by trim ASCII, lower case ASCII and the `kind_aliases` table.")
	w("2. If no dispatcher matches, return `unsupported_kind` without running any program.")
	w("3. Run the `pre_canonicalization_program` exactly once on the raw value. It")
	w("   runs as soon as the dispatcher is resolved, before any country decision,")
	w("   so a result that stops at step 4 still carries the pre-canonical value.")
	w("4. Normalize an explicit country by trim ASCII, upper case ASCII and the")
	w("   `country_aliases` table. A syntactically invalid token returns")
	w("   `unsupported_country`; in a country specific dispatcher a country without")
	w("   target also returns `unsupported_country`. An empty token behaves like an")
	w("   absent context.")
	w("5. Select the target owning the longest exactly matching `accepted_prefix`.")
	w("6. If an explicit country and a recognized prefix designate two different")
	w("   targets, return `country_mismatch`.")
	w("7. Select, in this order, the country target, the prefix target, the GLOBAL")
	w("   target, then the single `allow_unprefixed_without_country` target.")
	w("8. If nothing is selectable, return `missing_country_code`.")
	w("9. Run the canonicalization program of the selected definition exactly once on")
	w("   the pre-canonical value.")
	w("")
	w("A pre-canonicalization program is restricted to `SEQUENCE`, `TRIM_WHITESPACE`,")
	w("`REMOVE_WHITESPACE`, `UPPERCASE_ASCII` and `REMOVE_CHARS`. It can never add,")
	w("replace or interpret a prefix.")
	w("")
	w("### 5.1 Reported identity")
	w("")
	w("| Situation | `kind` | `canonicalValue` | `countryCode` |")
	w("|---|---|---|---|")
	w("| Input above the byte limit | requested token after trim and lower casing | raw input | raw context |")
	w("| Dispatcher not resolved | requested token after trim and lower casing | raw input | raw context |")
	w("| Dispatcher resolved, definition not selected | canonical kind | pre-canonical value | normalized country when one exists, otherwise the raw context |")
	w("| Definition selected | canonical kind | canonical value | country code of the target, or the normalized country context for a GLOBAL target |")
	w("")
	w("A GLOBAL target keeps a well formed country context in the result without using")
	w("it for routing. The country of a country target is its ISO 3166-1 alpha-2 code,")
	w("even when its business prefix differs, for example country `GR` with the")
	w("canonical VAT prefix `EL`.")
	w("")
	w("Two distinct notions share the name here, and confusing them changes results.")
	w("The `countryCode` of the report is the normalized country context, which a")
	w("GLOBAL target preserves. The `COUNTRY_CODE` string operation yields the country")
	w("of the selected target, which is absent for a GLOBAL target because such a")
	w("target has none. A GLOBAL definition can therefore report a country while")
	w("`COUNTRY_CODE` yields the absent string within the same evaluation.")
	w("")

	w("### 5.2 Effective profile")
	w("")
	w("The profile is resolved in two moments, because a definition cannot supply its")
	w("own default before it has been selected.")
	w("")
	w("Dispatch uses the profile of the caller, or `compatible` when the caller gives")
	w("none. This is the profile `PROFILE_IS` observes in a pre-canonicalization")
	w("program.")
	w("")
	w("Once a definition is selected, its `default_profile` applies when, and only")
	w("when, the caller supplied no profile. That resolved profile governs the format")
	w("and checksum programs, and is the profile reported in the result. A caller who")
	w("passes a profile explicitly always overrides the default.")
	w("")
	w("All current definitions declare `compatible`, so no conformance case separates")
	w("these rules today. They are normative regardless.")
	w("")
	w("## 6. Pipeline")
	w("")
	w("1. Reject a raw input longer than %d UTF-8 bytes with format", limits.MaxInputBytes)
	w("   `unsupported`/`input_too_long` and checksum `not_run`/`not_run_format_unsupported`.")
	w("2. Run the dispatch algorithm of section 5, each canonicalization phase at most once.")
	w("3. `country_mismatch` produces format `invalid`/`country_mismatch` and checksum")
	w("   `not_run`/`not_run_format_invalid`.")
	w("4. Any other dispatch failure produces format `unsupported` with that reason and")
	w("   checksum `not_run`/`not_run_format_unsupported`.")
	w("5. Run the format program on the canonical value.")
	w("6. An invalid format gives checksum `not_run`/`not_run_format_invalid`.")
	w("7. An unsupported format gives checksum `not_run`/`not_run_format_unsupported`.")
	w("8. A valid format without checksum program gives checksum `unsupported` with")
	w("   `absent_checksum_reason`.")
	w("9. A valid format with a checksum program runs it.")
	w("")
	w("`validateFormat` stops after step 5 and reports checksum")
	w("`not_run`/`not_requested` when the format is valid. `validateChecksum` returns")
	w("exactly the report of `validate`. `canonicalize` stops after step 2 and returns")
	w("`valid`/`ok`, `invalid`/`country_mismatch`, or `unsupported` with")
	w("`unsupported_kind`, `unsupported_country`, `missing_country_code` or")
	w("`input_too_long`.")
	w("")
	w("Results produced before a rule assertion never carry a message key. An assertion")
	w("or a checksum declared by the bundle keeps its message key exactly, including")
	w("when it is absent.")
	w("")

	w("## 7. Character classes")
	w("")
	w("The V1 classes are ASCII only: digits `U+0030..U+0039`, upper letters")
	w("`U+0041..U+005A`, lower letters `U+0061..U+007A`. `UPPERCASE_ASCII` maps only")
	w("`a..z` to `A..Z` and never consults a locale. Positions and lengths are counted")
	w("in Unicode code points.")
	w("")
	w("The frozen `whitespace_v1` table is:")
	w("")
	w("```text")
	w("U+0009..U+000D, U+0020, U+0085, U+00A0, U+1680,")
	w("U+2000..U+200A, U+2028, U+2029, U+202F, U+205F,")
	w("U+3000, U+FEFF")
	w("```")
	w("")
	w("A runtime must never delegate this definition to its own Unicode tables.")
	w("")
	w("The character mappings of `WEIGHTED_SUM` and `ISO7064_MOD97_10` are:")
	w("")
	w("| Mapping | Domain | Value |")
	w("|---|---|---|")
	w("| `CHAR_MAPPING_DIGIT_VALUE` | `0..9` | the decimal value |")
	w("| `CHAR_MAPPING_ALNUM_BASE36` | `0..9` and `A..Z` | the decimal value, then 10 to 35 |")
	w("")

	w("## 8. Limits")
	w("")
	w("Every limit is normative. An engine may raise an internal limit, never lower it.")
	w("")
	w("```text")
	w("maximum binary bundle          %d bytes", limits.MaxBundleBytes)
	w("maximum identifiers            %d", limits.MaxIdentifiers)
	w("maximum total nodes            %d", limits.MaxTotalNodes)
	w("maximum nodes per program      %d", limits.MaxNodesPerProgram)
	w("maximum call depth             %d", limits.MaxCallDepth)
	w("maximum constant string        %d UTF-8 bytes", limits.MaxConstantBytes)
	w("maximum user input             %d UTF-8 bytes", limits.MaxInputBytes)
	w("maximum steps per validation   %d", limits.MaxStepsPerValidation)
	w("code points billed as one step %d", limits.CodePointsPerStep)
	w("maximum captures per format    %d", limits.MaxCapturesPerFormat)
	w("```")
	w("")
	w("The bundle shaped limits are enforced when the bundle is accepted, whether by")
	w("a loader or by a generator, and no longer apply once code has been emitted.")
	w("The user input limit is an obligation of the engine itself: a longer input is")
	w("refused without being processed. The step budget applies only to an engine")
	w("that interprets.")
	w("")
	w("```text")
	w("integer constant                     signed int64")
	w("modulus / complement                 %d..%d", limits.MinModulus, limits.MaxModulus)
	w("absolute value of a weight           0..%d", limits.MaxWeightMagnitude)
	w("weights per operation                %d..%d", limits.MinWeights, limits.MaxWeights)
	w("elements of a remainder map          %d..%d", limits.MinRemainderValues, limits.MaxRemainderValues)
	w("index / slice bound                  0..%d", limits.MaxIndex)
	w("operands of concat                   %d..%d", limits.MinConcatOperands, limits.MaxConcatOperands)
	w("provable digits of digits_to_integer 1..%d", limits.MaxDigitsToIntegerLength)
	w("```")
	w("")

	w("## 9. Serialization order")
	w("")
	w("The compiler emits every repeated field in one normative order, and an")
	w("engine refuses a bundle that does not respect it: a stable order is what")
	w("makes the published SHA-256 meaningful and removes any dependence on the")
	w("iteration order of a hash map.")
	w("")
	w("| Field | Order |")
	w("|---|---|")
	w("| `RuleBundle.required_feature_ids` | strictly ascending |")
	w("| `RuleBundle.programs` | ascending `id` |")
	w("| `RuleBundle.identifiers` | `kind`, then GLOBAL first, then `country_code` |")
	w("| `RuleBundle.dispatchers` | UTF-8 bytes of `kind` |")
	w("| `IdentifierDefinition.sources` | UTF-8 bytes of `id` |")
	w("| `IdentifierDispatcher.kind_aliases` | UTF-8 bytes |")
	w("| `IdentifierDispatcher.country_aliases` | UTF-8 bytes of `alias` |")
	w("| `IdentifierDispatcher.targets` | GLOBAL first, then `country_code` |")
	w("| `DispatchTarget.accepted_prefixes` | UTF-8 bytes |")
	w("| `PredicateOperation.lengths` and `values` | ascending, deduplicated |")
	w("")
	w("Two equal sort keys are a rejected duplicate, never a tie broken by the")
	w("input order. Assertions, checksum branches, canonicalization steps,")
	w("weights, remainder tables and the topological node list keep their")
	w("semantic order and are never sorted.")
	w("")
	w("Identifier and program ids are assigned from 1 after sorting the fully")
	w("qualified symbol names of the sources by UTF-8 bytes. Nodes are emitted")
	w("by a deterministic post-order walk of the operands in syntactic order,")
	w("with an optional deduplication whose key is the deterministic Protobuf")
	w("encoding of the node itself, so two nodes are merged only when they are")
	w("observationally identical, operands, reason code and message key")
	w("included.")
	w("")
	w("The bundle carries no timestamp. `generatedAt` exists only in the")
	w("external manifest and is the UTC RFC 3339 representation of")
	w("`SOURCE_DATE_EPOCH`. An engine verifies the SHA-256 of the file it")
	w("received and never re-serializes a decoded message to recompute it,")
	w("because Protobuf is not a canonical serialization.")
	w("")

	w("## 10. Load time validation")
	w("")
	w("An engine performs these checks, in this order, before executing anything:")
	w("")
	for i, check := range loadChecks {
		w("%d. %s", i+1, check)
	}
	w("")
	w("A size, structural, arithmetic or graph violation is `invalid_ruleset`. An")
	w("unsupported `format_version` and an unknown capability id are")
	w("`incompatible_ruleset`. An engine never executes a partially validated graph and")
	w("never re-serializes a decoded message to verify the published SHA-256.")
	w("")
	w("An unknown operation is therefore `invalid_ruleset`, not `incompatible_ruleset`,")
	w("and the distinction is deliberate. A bundle that legitimately uses a newer")
	w("operation declares the capability that introduced it, so an engine too old to")
	w("understand it stops at check 5 with `incompatible_ruleset`. Reaching check 10")
	w("with an unknown operation means the bundle used one without declaring it, which")
	w("is a forged bundle rather than a version gap.")
	w("")
	w("A bundle whose encoding repeats a singular field, or carries two branches of the")
	w("same `oneof`, is not a valid bundle. A generator SHOULD refuse it. One that does")
	w("not inspect the wire encoding decodes it with the Protobuf semantics, and the")
	w("determinism of specification 2.4 is stated over valid bundles.")
	w("")
	return []byte(b.String())
}

// loadChecks is the normative load order reproduced in docs/ir.md.
var loadChecks = []string{
	"binary size at most 16 MiB",
	"complete Protobuf decoding",
	"absence of any unknown field at any depth",
	"supported `format_version`",
	"every `required_feature_ids` entry known, strictly ascending",
	"non empty `rules_version`",
	"`source_digest` of exactly 32 bytes",
	"program ids unique and non zero, program kinds specified",
	"node count within the per program and total limits",
	"every operation known, with its declared output type",
	"operand count, operand types and strictly lower operand indices",
	"only the parameters the operation declares, and every required parameter",
	"arithmetic bounds: moduli, weights, remainder tables, indices and provable integer widths",
	"root, subject and capture nodes inside the program and correctly typed",
	"program shape: accepted root per kind, `WHEN` only inside `CHOOSE`, and a " +
		"pre-canonicalization program restricted to its five permitted operations",
	"identifier ids unique, kinds and countries well formed, serialization order respected",
	"exactly one checksum program or one absence reason per definition",
	"dispatcher kinds and aliases globally unique, sorted, and never ambiguous",
	"country aliases sorted, unique, never self mapping and never shadowing a target",
	"targets sorted, unique per country, prefixes claimed by at most one target",
	"GLOBAL targets alone, without prefix and without country alias",
	"every definition referenced by exactly one dispatch target",
	"call graph acyclic, typed and of static depth at most 32",
	"no capability used without being declared",
}

func categoryIndex(c features.Category) int {
	for i, candidate := range features.Categories {
		if candidate == c {
			return i
		}
	}
	return 0
}

func valueTypeName(t irv1.ValueType) string {
	return irv1.ValueType_name[int32(t)]
}

func operandDescription(op features.Op) string {
	if op.MinOperands() == 0 && op.MaxOperands() == 0 {
		return "none"
	}
	var parts []string
	for _, o := range op.Operands {
		parts = append(parts, fmt.Sprintf("`%s` of type `%s`", o.Name, valueTypeName(o.Type)))
	}
	if op.Variadic != nil {
		bound := "unbounded"
		if op.MaxVariadic >= 0 {
			bound = fmt.Sprintf("at most %d", op.MaxVariadic)
		}
		parts = append(parts, fmt.Sprintf("then at least %d and %s repeated `%s` of type `%s`",
			op.MinVariadic, bound, op.Variadic.Name, valueTypeName(op.Variadic.Type)))
	}
	return strings.Join(parts, ", ")
}

func paramDescription(op features.Op) string {
	parts := make([]string, 0, len(op.Required)+len(op.Optional))
	for _, p := range op.Required {
		parts = append(parts, fmt.Sprintf("`%s` (required)", p))
	}
	for _, p := range op.Optional {
		parts = append(parts, fmt.Sprintf("`%s` (optional)", p))
	}
	if len(parts) == 0 {
		return "none; any other field present in the message is refused"
	}
	return strings.Join(parts, ", ") + "; any other field present in the message is refused"
}

func capabilityList(ids []uint32) string {
	sorted := append([]uint32(nil), ids...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i] < sorted[j] })
	var parts []string
	for _, id := range sorted {
		c, ok := features.Lookup(id)
		if !ok {
			continue
		}
		parts = append(parts, fmt.Sprintf("`%s` (%d)", c.Name, c.ID))
	}
	return strings.Join(parts, ", ")
}

func reasonCodeNames() []string {
	var names []string
	for value, name := range irv1.ReasonCode_name {
		if value == 0 {
			continue
		}
		names = append(names, strings.ToLower(strings.TrimPrefix(name, "REASON_CODE_")))
	}
	sort.Strings(names)
	return names
}

// The statuses a reason code can carry, as rendered in docs/ir.md.
const (
	statusValid       = "`valid`"
	statusInvalid     = "`invalid`"
	statusUnsupported = "`unsupported`"
	statusNotRun      = "`not_run`"
)

// reasonStatuses is the normative pairing reproduced in docs/ir.md.
var reasonStatuses = map[string]string{
	"ok":                         statusValid,
	"empty":                      statusInvalid,
	"invalid_length":             statusInvalid,
	"invalid_characters":         statusInvalid,
	"invalid_format":             statusInvalid,
	"invalid_checksum":           statusInvalid,
	"country_mismatch":           statusInvalid,
	"missing_country_code":       statusUnsupported,
	"unsupported_kind":           statusUnsupported,
	"unsupported_country":        statusUnsupported,
	"unsupported_format":         statusUnsupported,
	"unsupported_checksum":       statusUnsupported,
	"checksum_not_published":     statusUnsupported,
	"registry_not_configured":    statusUnsupported,
	"incompatible_ruleset":       statusUnsupported,
	"invalid_ruleset":            statusUnsupported,
	"input_too_long":             statusUnsupported,
	"not_requested":              statusNotRun,
	"not_run_format_invalid":     statusNotRun,
	"not_run_format_unsupported": statusNotRun,
}

func statusesFor(reason string) string {
	if s, ok := reasonStatuses[reason]; ok {
		return s
	}
	return "unspecified"
}

// titleASCII upper cases the first ASCII letter of a word.
func titleASCII(s string) string {
	if s == "" {
		return s
	}
	b := []byte(s)
	if b[0] >= 'a' && b[0] <= 'z' {
		b[0] -= 'a' - 'A'
	}
	return string(b)
}
