#!/usr/bin/env python3
"""Decoder security conformance corpus."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_conformance import KEY_ORDER, order, write  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

FIXTURES = [
    ("truncated.binpb", "invalid_ruleset", "A truncated bundle is refused before any execution", ["decoder", "security", "truncation"]),
    ("empty.binpb", "incompatible_ruleset", "An empty payload carries no supported format version", ["decoder", "security", "version"]),
    ("unknown_field_root.binpb", "invalid_ruleset", "An unknown Protobuf field is refused at any depth", ["decoder", "security", "unknown-field"]),
    ("unsupported_format_version.binpb", "incompatible_ruleset", "An unsupported IR format version closes the execution", ["decoder", "security", "version"]),
    ("unknown_feature.binpb", "incompatible_ruleset", "A single unknown capability id closes the execution", ["capabilities", "decoder", "security"]),
    ("undeclared_feature.binpb", "invalid_ruleset", "A capability used but not declared is refused", ["capabilities", "decoder", "security"]),
    ("short_digest.binpb", "invalid_ruleset", "A digest of the wrong length is refused", ["decoder", "digest", "security"]),
    ("empty_rules_version.binpb", "invalid_ruleset", "An empty business version is refused", ["decoder", "security", "version"]),
    ("missing_operation.binpb", "invalid_ruleset", "A node without operation oneof is refused", ["decoder", "graph", "security"]),
    ("node_forward_reference.binpb", "invalid_ruleset", "A node referencing a higher index is refused", ["decoder", "graph", "security"]),
    ("node_out_of_range.binpb", "invalid_ruleset", "A root node outside the program is refused", ["decoder", "graph", "security"]),
    ("type_mismatch.binpb", "invalid_ruleset", "An operand of the wrong type is refused", ["decoder", "graph", "security", "types"]),
    ("unspecified_enum.binpb", "invalid_ruleset", "An UNSPECIFIED enum value is refused", ["decoder", "enum", "security"]),
    ("call_cycle.binpb", "invalid_ruleset", "A self recursive call graph is refused", ["cycle", "decoder", "security"]),
    ("unknown_call_target.binpb", "invalid_ruleset", "A call towards an unknown program is refused", ["decoder", "graph", "security"]),
    ("orphan_definition.binpb", "invalid_ruleset", "A definition no dispatcher references is refused", ["decoder", "dispatch", "security"]),
    ("duplicate_prefix.binpb", "invalid_ruleset", "The same prefix claimed by two targets is refused", ["decoder", "dispatch", "security"]),
    ("forbidden_reason_code.binpb", "invalid_ruleset", "A reason code that cannot prove an invalidity is refused", ["decoder", "reason-code", "security"]),
    ("stray_parameter.binpb", "invalid_ruleset", "A parameter foreign to the operation is refused", ["decoder", "parameters", "security"]),
    ("unbounded_digits_to_integer.binpb", "invalid_ruleset", "An unprovable digits_to_integer bound is refused", ["arithmetic", "decoder", "security"]),
    ("modulus_out_of_range.binpb", "invalid_ruleset", "A modulus outside the accepted range is refused", ["arithmetic", "decoder", "security"]),
    ("stray_when_branch.binpb", "invalid_ruleset", "A WHEN branch outside a CHOOSE is refused", ["checksum", "decoder", "security"]),
    ("global_target_with_prefix.binpb", "invalid_ruleset", "A GLOBAL target declaring a prefix is refused", ["decoder", "dispatch", "security"]),
]

cases = []
for index, (fixture, expected, description, tags) in enumerate(FIXTURES, start=1):
    name = fixture.replace(".binpb", "").replace("_", "-")
    cases.append({
        "id": f"loader-{name}-{index:03d}",
        "description": description,
        "operation": "load_ruleset",
        "tags": sorted(set(tags)),
        "fixture": f"bundles/{fixture}",
        "expectedEngineError": expected,
        "dataClassification": "synthetic",
        "redistributionBasis": "Synthetic decoder fixture generated by tools/genfixtures.go; holds no identifier value.",
    })

write(os.path.join(ROOT, "conformance", "global", "security.jsonl"), cases)
